<../../../mkconfig

TARG=\
	ida.dis\
	idatab.dis\

MODULES=\

SYSMODULES= \
	ida.m\
	rand.m\
	sys.m\

DISBIN=$BUILDROOT/dis/lib/ida

<$ROOT/mkfiles/mkdis
# force compilation
LIMBOFLAGS= -c $LIMBOFLAGS

idatab.dis:	idatab.dist
	cp idatab.dist idatab.dis
