<../../../mkconfig

TARG=\
	buildstrokes.dis\
	strokes.dis\
	readstrokes.dis\
	writestrokes.dis\

MODULES=

SYSMODULES= \
	bufio.m\
	strokes.m\
	sys.m\

DISBIN=$BUILDROOT/dis/lib/strokes

<$ROOT/mkfiles/mkdis
